# Generated by Django 4.1.3 on 2022-12-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
